import Head from 'next/head'
import Tabs from "@/src/components/main/home/tabs";
import VerticalLinearStepper from "@/src/components/main/home/stepper";
import { Box, Grid } from "@mui/material"

export default function Home() {
  return (
    <>
      <Head>
        <title>Qusetion App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Box sx={{
          mt: -13,
          mx: -2,
        }}>
          <Grid container spacing={4}>
            <Grid item md={10}>
              <Tabs />
            </Grid>
            <Grid item md={2}>
              <VerticalLinearStepper />
            </Grid>
          </Grid>
        </Box>
      </main>
    </>
  )
}
